### ISSUE TITLE
Generalize fs2<->akka compat to F: Effect instead of IO

### ISSUE THREAD

**Issue by Daenyth** [krasserm/streamz#47] opened 2018-04-24 14:16 UTC
I'd like to use streamz-converter with any Effect instead of just IO.

I glanced at the code and haven't spotted anywhere that this would be difficult, though I could have missed it of course.

If this change is acceptable I might submit a PR for it.

**Comment by krasserm** [comment] 2018-04-24 16:41
Did you see #46 ?

**Comment by krasserm** [comment] 2018-04-25 07:38
Closing as duplicate of #46. Your feedback on that PR is welcome!

**Closed by krasserm** 2018-04-25 07:38 UTC
